<?php

return [
    'providers' => [
        'Illuminate\\Auth\\AuthServiceProvider',
        'Illuminate\\Broadcasting\\BroadcastServiceProvider',
        'Illuminate\\Bus\\BusServiceProvider',
        'Illuminate\\Cache\\CacheServiceProvider',
        'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider',
        'Illuminate\\Concurrency\\ConcurrencyServiceProvider',
        'Illuminate\\Cookie\\CookieServiceProvider',
        'Illuminate\\Database\\DatabaseServiceProvider',
        'Illuminate\\Encryption\\EncryptionServiceProvider',
        'Illuminate\\Filesystem\\FilesystemServiceProvider',
        'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
        'Illuminate\\Hashing\\HashServiceProvider',
        'Illuminate\\Mail\\MailServiceProvider',
        'Illuminate\\Notifications\\NotificationServiceProvider',
        'Illuminate\\Pagination\\PaginationServiceProvider',
        'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider',
        'Illuminate\\Pipeline\\PipelineServiceProvider',
        'Illuminate\\Queue\\QueueServiceProvider',
        'Illuminate\\Redis\\RedisServiceProvider',
        'Illuminate\\Session\\SessionServiceProvider',
        'Illuminate\\Translation\\TranslationServiceProvider',
        'Illuminate\\Validation\\ValidationServiceProvider',
        'Illuminate\\View\\ViewServiceProvider',
        'Barryvdh\\Debugbar\\ServiceProvider',
        'ChrisKonnertz\\OpenGraph\\OpenGraphServiceProvider',
        'Cviebrock\\EloquentSluggable\\ServiceProvider',
        'Intervention\\Image\\Laravel\\ServiceProvider',
        'Jaybizzle\\LaravelCrawlerDetect\\LaravelCrawlerDetectServiceProvider',
        'Knuckles\\Scribe\\ScribeServiceProvider',
        'Laracasts\\Flash\\FlashServiceProvider',
        'NotificationChannels\\Twilio\\TwilioProvider',
        'Laravel\\Pail\\PailServiceProvider',
        'Laravel\\Sail\\SailServiceProvider',
        'Laravel\\Sanctum\\SanctumServiceProvider',
        'Laravel\\Socialite\\SocialiteServiceProvider',
        'Laravel\\Tinker\\TinkerServiceProvider',
        'Illuminate\\Notifications\\VonageChannelServiceProvider',
        'MailerSend\\LaravelDriver\\LaravelDriverServiceProvider',
        'Bedigit\\Breadcrumbs\\BreadcrumbServiceProvider',
        'Mews\\Purifier\\PurifierServiceProvider',
        'Carbon\\Laravel\\ServiceProvider',
        'NunoMaduro\\Collision\\Adapters\\Laravel\\CollisionServiceProvider',
        'Termwind\\Laravel\\TermwindServiceProvider',
        'Prologue\\Alerts\\AlertsServiceProvider',
        'Spatie\\Backup\\BackupServiceProvider',
        'Spatie\\CookieConsent\\CookieConsentServiceProvider',
        'Spatie\\Html\\HtmlServiceProvider',
        'Spatie\\LaravelIgnition\\IgnitionServiceProvider',
        'Spatie\\Permission\\PermissionServiceProvider',
        'Spatie\\LaravelRay\\RayServiceProvider',
        'Spatie\\SignalAwareCommand\\SignalAwareCommandServiceProvider',
        'Spatie\\Translatable\\TranslatableServiceProvider',
        'Vemcogroup\\SparkPostDriver\\SparkPostDriverServiceProvider',
        'Watson\\Sitemap\\SitemapServiceProvider',
        'App\\Providers\\AliasServiceProvider',
        'App\\Providers\\AppServiceProvider',
        'App\\Providers\\AuthServiceProvider',
        'App\\Providers\\PluginServiceProvider',
        'App\\Providers\\MacroServiceProvider',
        'App\\Providers\\ExtensionServiceProvider',
        'Larapen\\TextToImage\\TextToImageServiceProvider',
        'Larapen\\LaravelMetaTags\\MetaTagsServiceProvider',
        'Larapen\\Honeypot\\HoneypotServiceProvider',
        'Larapen\\Captcha\\CaptchaServiceProvider',
        'Larapen\\ReCaptcha\\ReCaptchaServiceProvider',
        'Larapen\\LaravelDistance\\DistanceServiceProvider',
        'Larapen\\Feed\\FeedServiceProvider',
        'Larapen\\Impersonate\\ImpersonateServiceProvider',
    ],

    'eager' => [
        'Illuminate\\Auth\\AuthServiceProvider',
        'Illuminate\\Cookie\\CookieServiceProvider',
        'Illuminate\\Database\\DatabaseServiceProvider',
        'Illuminate\\Encryption\\EncryptionServiceProvider',
        'Illuminate\\Filesystem\\FilesystemServiceProvider',
        'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
        'Illuminate\\Notifications\\NotificationServiceProvider',
        'Illuminate\\Pagination\\PaginationServiceProvider',
        'Illuminate\\Session\\SessionServiceProvider',
        'Illuminate\\View\\ViewServiceProvider',
        'Barryvdh\\Debugbar\\ServiceProvider',
        'ChrisKonnertz\\OpenGraph\\OpenGraphServiceProvider',
        'Cviebrock\\EloquentSluggable\\ServiceProvider',
        'Intervention\\Image\\Laravel\\ServiceProvider',
        'Jaybizzle\\LaravelCrawlerDetect\\LaravelCrawlerDetectServiceProvider',
        'Knuckles\\Scribe\\ScribeServiceProvider',
        'Laracasts\\Flash\\FlashServiceProvider',
        'Laravel\\Pail\\PailServiceProvider',
        'Laravel\\Sanctum\\SanctumServiceProvider',
        'Illuminate\\Notifications\\VonageChannelServiceProvider',
        'MailerSend\\LaravelDriver\\LaravelDriverServiceProvider',
        'Bedigit\\Breadcrumbs\\BreadcrumbServiceProvider',
        'Mews\\Purifier\\PurifierServiceProvider',
        'Carbon\\Laravel\\ServiceProvider',
        'NunoMaduro\\Collision\\Adapters\\Laravel\\CollisionServiceProvider',
        'Termwind\\Laravel\\TermwindServiceProvider',
        'Prologue\\Alerts\\AlertsServiceProvider',
        'Spatie\\Backup\\BackupServiceProvider',
        'Spatie\\CookieConsent\\CookieConsentServiceProvider',
        'Spatie\\Html\\HtmlServiceProvider',
        'Spatie\\LaravelIgnition\\IgnitionServiceProvider',
        'Spatie\\Permission\\PermissionServiceProvider',
        'Spatie\\LaravelRay\\RayServiceProvider',
        'Spatie\\SignalAwareCommand\\SignalAwareCommandServiceProvider',
        'Spatie\\Translatable\\TranslatableServiceProvider',
        'Vemcogroup\\SparkPostDriver\\SparkPostDriverServiceProvider',
        'Watson\\Sitemap\\SitemapServiceProvider',
        'App\\Providers\\AliasServiceProvider',
        'App\\Providers\\AppServiceProvider',
        'App\\Providers\\AuthServiceProvider',
        'App\\Providers\\PluginServiceProvider',
        'App\\Providers\\MacroServiceProvider',
        'App\\Providers\\ExtensionServiceProvider',
        'Larapen\\TextToImage\\TextToImageServiceProvider',
        'Larapen\\LaravelMetaTags\\MetaTagsServiceProvider',
        'Larapen\\Honeypot\\HoneypotServiceProvider',
        'Larapen\\Captcha\\CaptchaServiceProvider',
        'Larapen\\ReCaptcha\\ReCaptchaServiceProvider',
        'Larapen\\LaravelDistance\\DistanceServiceProvider',
        'Larapen\\Feed\\FeedServiceProvider',
        'Larapen\\Impersonate\\ImpersonateServiceProvider',
    ],

    'deferred' => [
        'Illuminate\\Broadcasting\\BroadcastManager' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
        'Illuminate\\Contracts\\Broadcasting\\Factory' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
        'Illuminate\\Contracts\\Broadcasting\\Broadcaster' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
        'Illuminate\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
        'Illuminate\\Contracts\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
        'Illuminate\\Contracts\\Bus\\QueueingDispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
        'Illuminate\\Bus\\BatchRepository' => 'Illuminate\\Bus\\BusServiceProvider',
        'Illuminate\\Bus\\DatabaseBatchRepository' => 'Illuminate\\Bus\\BusServiceProvider',
        'cache' => 'Illuminate\\Cache\\CacheServiceProvider',
        'cache.store' => 'Illuminate\\Cache\\CacheServiceProvider',
        'cache.psr6' => 'Illuminate\\Cache\\CacheServiceProvider',
        'memcached.connector' => 'Illuminate\\Cache\\CacheServiceProvider',
        'Illuminate\\Cache\\RateLimiter' => 'Illuminate\\Cache\\CacheServiceProvider',
        'Illuminate\\Foundation\\Console\\*' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider',
        'Illuminate\\Concurrency\\ConcurrencyManager' => 'Illuminate\\Concurrency\\ConcurrencyServiceProvider',
        'hash' => 'Illuminate\\Hashing\\HashServiceProvider',
        'hash.driver' => 'Illuminate\\Hashing\\HashServiceProvider',
        'mail.manager' => 'Illuminate\\Mail\\MailServiceProvider',
        'mailer' => 'Illuminate\\Mail\\MailServiceProvider',
        'Illuminate\\Mail\\Markdown' => 'Illuminate\\Mail\\MailServiceProvider',
        'auth.password' => 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider',
        'auth.password.broker' => 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider',
        'pipeline' => 'Illuminate\\Pipeline\\PipelineServiceProvider',
        'queue' => 'Illuminate\\Queue\\QueueServiceProvider',
        'queue.connection' => 'Illuminate\\Queue\\QueueServiceProvider',
        'queue.failer' => 'Illuminate\\Queue\\QueueServiceProvider',
        'queue.listener' => 'Illuminate\\Queue\\QueueServiceProvider',
        'queue.worker' => 'Illuminate\\Queue\\QueueServiceProvider',
        'redis' => 'Illuminate\\Redis\\RedisServiceProvider',
        'redis.connection' => 'Illuminate\\Redis\\RedisServiceProvider',
        'translator' => 'Illuminate\\Translation\\TranslationServiceProvider',
        'translation.loader' => 'Illuminate\\Translation\\TranslationServiceProvider',
        'validator' => 'Illuminate\\Validation\\ValidationServiceProvider',
        'validation.presence' => 'Illuminate\\Validation\\ValidationServiceProvider',
        'Illuminate\\Contracts\\Validation\\UncompromisedVerifier' => 'Illuminate\\Validation\\ValidationServiceProvider',
        'NotificationChannels\\Twilio\\TwilioChannel' => 'NotificationChannels\\Twilio\\TwilioProvider',
        'NotificationChannels\\Twilio\\TwilioConfig' => 'NotificationChannels\\Twilio\\TwilioProvider',
        'Twilio\\Rest\\Client' => 'NotificationChannels\\Twilio\\TwilioProvider',
        'Laravel\\Sail\\Console\\InstallCommand' => 'Laravel\\Sail\\SailServiceProvider',
        'Laravel\\Sail\\Console\\PublishCommand' => 'Laravel\\Sail\\SailServiceProvider',
        'Laravel\\Socialite\\Contracts\\Factory' => 'Laravel\\Socialite\\SocialiteServiceProvider',
        'command.tinker' => 'Laravel\\Tinker\\TinkerServiceProvider',
    ],

    'when' => [
        'Illuminate\\Broadcasting\\BroadcastServiceProvider' => [],
        'Illuminate\\Bus\\BusServiceProvider' => [],
        'Illuminate\\Cache\\CacheServiceProvider' => [],
        'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider' => [],
        'Illuminate\\Concurrency\\ConcurrencyServiceProvider' => [],
        'Illuminate\\Hashing\\HashServiceProvider' => [],
        'Illuminate\\Mail\\MailServiceProvider' => [],
        'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider' => [],
        'Illuminate\\Pipeline\\PipelineServiceProvider' => [],
        'Illuminate\\Queue\\QueueServiceProvider' => [],
        'Illuminate\\Redis\\RedisServiceProvider' => [],
        'Illuminate\\Translation\\TranslationServiceProvider' => [],
        'Illuminate\\Validation\\ValidationServiceProvider' => [],
        'NotificationChannels\\Twilio\\TwilioProvider' => [],
        'Laravel\\Sail\\SailServiceProvider' => [],
        'Laravel\\Socialite\\SocialiteServiceProvider' => [],
        'Laravel\\Tinker\\TinkerServiceProvider' => [],
    ],
];