# ==============================================================================
# LaraClassifier GitHub Actions CI/CD Pipeline for Coolify
# ==============================================================================
# Location: .github/workflows/deploy.yml
#
# This workflow handles:
# - Code testing (PHPUnit, Pint)
# - Asset building
# - Docker image building and pushing
# - Coolify deployment via webhook
#
# Required Secrets:
#   - DOCKER_USERNAME: Docker Hub username
#   - DOCKER_PASSWORD: Docker Hub password/token
#   - COOLIFY_WEBHOOK_URL: Coolify deployment webhook URL
#   - COOLIFY_WEBHOOK_TOKEN: Coolify webhook authentication token
#   - SLACK_WEBHOOK_URL: Slack webhook URL for notifications (optional)
#
# Coolify handles the actual deployment, so SSH-based deployment is removed.
# ==============================================================================

name: LaraClassifier CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      skip_tests:
        description: 'Skip tests (emergency deploy)'
        required: false
        default: false
        type: boolean

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables
env:
  PHP_VERSION: '8.2'
  NODE_VERSION: '20'
  COMPOSER_VERSION: '2'
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/laraclassifier
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

jobs:
  # ===========================================================================
  # Test Job
  # ===========================================================================
  test:
    name: Test & Analyze
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tests }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, mysql, curl, zip, intl, gd, bcmath, redis, opcache
          coverage: xdebug
          tools: composer:v${{ env.COMPOSER_VERSION }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      
      - name: Install PHP dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      
      - name: Install NPM dependencies
        run: npm ci
      
      - name: Copy environment file
        run: cp .env.example .env || true
      
      - name: Generate application key
        run: php artisan key:generate --force || true
      
      - name: Create storage symlink
        run: php artisan storage:link || true
      
      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache
      
      - name: Run PHPStan (Static Analysis)
        run: vendor/bin/phpstan analyse --memory-limit=2G || true
        continue-on-error: true
      
      - name: Run Laravel Pint (Code Style)
        run: vendor/bin/pint --test || true
        continue-on-error: true
      
      - name: Run PHPUnit tests
        run: php artisan test --parallel --coverage-clover=coverage.xml
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
        continue-on-error: true
      
      - name: Run security check
        uses: symfonycorp/security-checker-action@v3
        continue-on-error: true

  # ===========================================================================
  # Build Job
  # ===========================================================================
  build:
    name: Build Assets
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install NPM dependencies
        run: npm ci
      
      - name: Build production assets
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: |
            public/build/
            public/css/
            public/js/
            public/mix-manifest.json
          retention-days: 1

  # ===========================================================================
  # Docker Build & Push Job
  # ===========================================================================
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-assets
          path: public/
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/staging' }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployment/docker/Dockerfile
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          build-args: |
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_URL=${{ secrets.APP_URL }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
      
      - name: Output image digest
        run: echo ${{ steps.build.outputs.digest }}

  # ===========================================================================
  # Deploy to Staging via Coolify Webhook
  # ===========================================================================
  deploy-staging:
    name: Deploy to Staging (Coolify)
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/staging' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment:
      name: staging
      url: https://staging.your-domain.com
    
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST "${{ secrets.COOLIFY_STAGING_WEBHOOK_URL }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_WEBHOOK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "force": true,
              "docker_image": "${{ env.DOCKER_IMAGE }}:staging"
            }'
      
      - name: Wait for deployment
        run: sleep 30
      
      - name: Health check
        run: |
          for i in {1..10}; do
            if curl -sSf https://staging.your-domain.com/health; then
              echo "Health check passed"
              exit 0
            fi
            echo "Health check attempt $i failed, retrying..."
            sleep 10
          done
          echo "Health check failed after 10 attempts"
          exit 1
      
      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Staging deployment ${{ job.status }}'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # ===========================================================================
  # Deploy to Production via Coolify Webhook
  # ===========================================================================
  deploy-production:
    name: Deploy to Production (Coolify)
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    environment:
      name: production
      url: https://your-domain.com
    
    steps:
      - name: Create deployment tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          TAG="deploy-$(date +%Y%m%d-%H%M%S)"
          git tag -a "$TAG" -m "Deployment to production"
          git push origin "$TAG" || true
        continue-on-error: true
      
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST "${{ secrets.COOLIFY_PRODUCTION_WEBHOOK_URL }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_WEBHOOK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "force": true,
              "docker_image": "${{ env.DOCKER_IMAGE }}:latest"
            }'
      
      - name: Wait for deployment
        run: sleep 60
      
      - name: Health check
        run: |
          for i in {1..15}; do
            if curl -sSf https://your-domain.com/health; then
              echo "Health check passed"
              exit 0
            fi
            echo "Health check attempt $i failed, retrying..."
            sleep 10
          done
          echo "Health check failed after 15 attempts"
          exit 1
      
      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Production deployment ${{ job.status }}'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # ===========================================================================
  # Notify on Failure
  # ===========================================================================
  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [test, build, docker]
    if: failure()
    
    steps:
      - name: Notify Slack on failure
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: 'CI/CD Pipeline Failed'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

# ==============================================================================
# Notes
# ==============================================================================
#
# SETUP INSTRUCTIONS:
#
# 1. Create Docker Hub Account:
#    - Sign up at https://hub.docker.com
#    - Create a repository named 'laraclassifier'
#
# 2. Configure GitHub Secrets:
#    - Go to repository Settings > Secrets and variables > Actions
#    - Add the following secrets:
#      - DOCKER_USERNAME: Your Docker Hub username
#      - DOCKER_PASSWORD: Docker Hub access token (create in Account Settings)
#      - COOLIFY_STAGING_WEBHOOK_URL: Staging deployment webhook URL
#      - COOLIFY_PRODUCTION_WEBHOOK_URL: Production deployment webhook URL
#      - COOLIFY_WEBHOOK_TOKEN: Coolify webhook authentication token
#      - SLACK_WEBHOOK_URL: Slack webhook for notifications (optional)
#      - APP_KEY: Laravel application key
#      - APP_URL: Application URL
#
# 3. Get Coolify Webhook URLs:
#    - In Coolify dashboard, go to Application > Webhooks
#    - Copy the deployment webhook URL
#    - Generate an API token in Coolify settings
#
# 4. Test the Pipeline:
#    - Push to 'staging' branch for staging deployment
#    - Push to 'main' branch for production deployment
#    - Or use manual workflow dispatch
#
# DEPLOYMENT FLOW:
#
# 1. Code is pushed to GitHub
# 2. Tests run automatically
# 3. Assets are built
# 4. Docker image is built and pushed to Docker Hub
# 5. Coolify webhook is triggered
# 6. Coolify pulls the new image and deploys
# 7. Health check verifies deployment
# 8. Notification is sent to Slack
#
# ==============================================================================